package com.xkorey.mybatis.dao;

import org.apache.ibatis.annotations.Mapper;

import com.xkorey.mybatis.models.FunLog;

@Mapper
public interface FunLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fun_log
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fun_log
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    int insert(FunLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fun_log
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    int insertSelective(FunLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fun_log
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    FunLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fun_log
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    int updateByPrimaryKeySelective(FunLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fun_log
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(FunLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fun_log
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    int updateByPrimaryKey(FunLog record);
}