package com.xkorey.mybatis.models;

public class FunLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fun_log.id
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fun_log.user_id
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    private Long user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fun_log.info
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fun_log.id
     *
     * @return the value of fun_log.id
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fun_log.id
     *
     * @param id the value for fun_log.id
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fun_log.user_id
     *
     * @return the value of fun_log.user_id
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fun_log.user_id
     *
     * @param user_id the value for fun_log.user_id
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fun_log.info
     *
     * @return the value of fun_log.info
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fun_log.info
     *
     * @param info the value for fun_log.info
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    public void setInfo(String info) {
        this.info = info;
    }
}