package com.xkorey.mybatis.models;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userName
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userAge
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    private Integer userAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userAddress
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    private String userAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userName
     *
     * @return the value of user.userName
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userName
     *
     * @param userName the value for user.userName
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userAge
     *
     * @return the value of user.userAge
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userAge
     *
     * @param userAge the value for user.userAge
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userAddress
     *
     * @return the value of user.userAddress
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userAddress
     *
     * @param userAddress the value for user.userAddress
     *
     * @mbg.generated Mon Apr 03 20:43:10 CST 2017
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
}